version: "3.9"

services:
  app:
    build: .
    container_name: sr_devops
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: sr_devops_redis
    ports:
      - "6379:6379"